-- Generated with g9.
--
-- Run this schema script against Derby as follows:
-- java org.apache.derby.tools.ij hotelsystem-schema.sql


-- CREATE TABLE statements including basic column definitions
CREATE TABLE Answer (
  stringResponse varchar(2048),
  integerResponse integer,
  numericResponse decimal(10,3),
  booleanResponse smallint,
  enumResponse integer CHECK (enumResponse IN (1,2,3)),
  comment varchar(1024),
  id integer NOT NULL,
  question_id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Booking (
  fromDate date,
  toDate date,
  id integer generated by default as identity NOT NULL,
  customer_customerNo integer NOT NULL,
  hotel_id integer NOT NULL,
  roomCategory_id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Company (
  name varchar(40),
  postalAddress varchar(40),
  postalCode integer,
  organizationId integer NOT NULL,
  customer_customerNo integer NOT NULL UNIQUE,
  LOCK_FLAG integer,
  PRIMARY KEY (organizationId)
);

CREATE TABLE Customer (
  creditCard varchar(16),
  customerNo integer NOT NULL,
  email varchar(40),
  name varchar(40),
  password varchar(40),
  phone varchar(20),
  custodian integer,
  LOCK_FLAG integer,
  PRIMARY KEY (customerNo)
);

CREATE TABLE CustomerSatisfactionQuestionnr (
  dateResponded date,
  id integer NOT NULL,
  questionnaire_id integer NOT NULL,
  respondee_customerNo integer,
  visitedHotels_id integer,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Hotel (
  id integer NOT NULL,
  location varchar(30),
  logo varchar(40),
  name varchar(40),
  chain_id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE HotelChain (
  name varchar(40) NOT NULL,
  id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE HotelRoomCategory (
  actualPrice integer,
  fromDate date NOT NULL,
  toDate date,
  hotel_id integer NOT NULL,
  roomCategory_id integer NOT NULL,
  LOCK_FLAG integer,
  CONSTRAINT HotelRoomCategory_PK PRIMARY KEY (hotel_id,roomCategory_id,fromDate)
);

CREATE TABLE Invoice (
  invoiceNo integer NOT NULL,
  invoiceText varchar(100),
  customer_customerNo integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (invoiceNo)
);

CREATE TABLE Night (
  id integer NOT NULL,
  date date,
  price integer,
  room_id integer NOT NULL,
  stay_customer_customerNo integer NOT NULL,
  stay_serialNo integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Address (
  homeAddress varchar(40),
  postalCode integer,
  id integer NOT NULL,
  customer_customerNo integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE QuestionTemplate (
  questionText varchar(512),
  hasComment smallint,
  responseType integer CHECK (responseType IN (0,1,2,3,4)),
  rank integer,
  id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Questionnaire (
  name varchar(255),
  description varchar(1024),
  startDate date,
  endDate date,
  id integer NOT NULL,
  questions_id integer,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE RankMapping (
  number integer,
  name varchar(40),
  id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Room (
  roomNo integer,
  floor integer,
  balcony smallint,
  heading integer CHECK (heading IN (1,2,3,4)),
  id integer NOT NULL,
  category_id integer NOT NULL,
  hotel_id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE RoomCategory (
  bedType integer CHECK (bedType IN (1,2,3,4,5)),
  guests integer,
  id integer NOT NULL,
  initialPrice integer,
  maxDiscount integer,
  roomQuality integer CHECK (roomQuality IN (1,2,3)),
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

CREATE TABLE Stay (
  serialNo integer NOT NULL,
  booking_id integer,
  customer_customerNo integer NOT NULL,
  invoice_invoiceNo integer,
  location_id integer NOT NULL,
  LOCK_FLAG integer,
  CONSTRAINT Stay_PK PRIMARY KEY (customer_customerNo,serialNo)
);

CREATE TABLE TemplateBooking (
  id integer NOT NULL,
  customer_customerNo integer NOT NULL,
  hotel_id integer NOT NULL,
  roomCategory_id integer NOT NULL,
  LOCK_FLAG integer,
  PRIMARY KEY (id)
);

